language: node_js
node_js:
  - lts/*
install:
  - npm ci
before_install:
  - export TZ=Asia/Taipei
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
